"""Fresh migration

Revision ID: 5f85aabfd1a1
Revises: 
Create Date: 2025-03-25 11:10:37.645522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f85aabfd1a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_id'))

    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
